name: retro95
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  flutter95: ^0.0.7

  reorderables: ^0.3.2

  intl: ^0.16.1

  freezed_annotation:

  custom_navigator: ^0.1.1

  easy_web_view: 1.2.0

  easy_google_maps: 1.0.0+2

  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
    
  freezed:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

